--[[
Autogenerated Test File for observables
--]]

package.path = package.path..package.path:gsub("Framework","FakedFiles");
-------------------------------------Define setup code here for fake files here--------------------------------------

--------------------------------------------------End of Setup Code--------------------------------------------------

require("BlizzardFakes");
require("UnitTest");
require("Fakeobservables");


-----------------------------------------Define generel Test setup code here-----------------------------------------

--------------------------------------------------End of Setup Code--------------------------------------------------

function TEST_Observable_new()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_Observable_registerObserver()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_Observable_unregisterObserver()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_Observable_notify()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_Observable_set()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_Observable_get()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_ObservableNumber_new()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_ObservableNumber_add()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_ObservableNumber_sub()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_ObservableNumber_mul()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_ObservableNumber_divBy()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_ObservableString_new()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_ObservableBool_new()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

UnitTest_vSetupTests();
TEST_Observable_new();
TEST_Observable_registerObserver();
TEST_Observable_unregisterObserver();
TEST_Observable_notify();
TEST_Observable_set();
TEST_Observable_get();
TEST_ObservableNumber_new();
TEST_ObservableNumber_add();
TEST_ObservableNumber_sub();
TEST_ObservableNumber_mul();
TEST_ObservableNumber_divBy();
TEST_ObservableString_new();
TEST_ObservableBool_new();
UnitTest_vFinalizeTests();
