--[[
Autogenerated Test File for AutoRollAnalyser
--]]

package.path = package.path..
package.path:gsub("Framework","FakedFiles")..
package.path:gsub("Tests\\Framework","Lang");
-------------------------------------Define setup code here for fake files here--------------------------------------
StriLi = {};
--------------------------------------------------End of Setup Code--------------------------------------------------

require("BlizzardFakes");
require("enGB");
require("Language");
require("UnitTest");
require("FakeAutoRollAnalyser");

-----------------------------------------Define generel Test setup code here-----------------------------------------
TEST_StriLi = {AutoRollAnalyser = {}};
StriLi.InitLang();
--------------------------------------------------End of Setup Code--------------------------------------------------

function TEST_StriLi.AutoRollAnalyser:setItemID()
	UnitTest_vStartTest();

	--Test1
	StriLi.AutoRollAnalyser:setItemID(0)
	UnitTest_vTestAssert(StriLi.AutoRollAnalyser.itemID == 0);
	
	--Test2
	StriLi.AutoRollAnalyser:setItemID(65536)
	UnitTest_vTestAssert(StriLi.AutoRollAnalyser.itemID == 65536);
	
	--Test3
	StriLi.AutoRollAnalyser.rollInProgress = true;
	StriLi.AutoRollAnalyser:setItemID(0)
	UnitTest_vTestAssert(StriLi.AutoRollAnalyser.itemID == 65536);
	
	StriLi.AutoRollAnalyser.rollInProgress = false;

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:setTimeForRolls()
	UnitTest_vStartTest();

	--Test1
	StriLi.AutoRollAnalyser:setTimeForRolls(0)
	UnitTest_vTestAssert(StriLi.AutoRollAnalyser.time == 0);
	
	--Test2
	StriLi.AutoRollAnalyser:setTimeForRolls(100)
	UnitTest_vTestAssert(StriLi.AutoRollAnalyser.time == 100);
	
	--Test3
	StriLi.AutoRollAnalyser:setTimeForRolls(0.3)
	UnitTest_vTestAssert(StriLi.AutoRollAnalyser.time == 0.3);
	
	--Test4
	StriLi.AutoRollAnalyser.rollInProgress = true;
	StriLi.AutoRollAnalyser:setTimeForRolls(10)
	UnitTest_vTestAssert(StriLi.AutoRollAnalyser.time == 0.3);
	
	StriLi.AutoRollAnalyser.rollInProgress = false;

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:setItem()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:getRollInProgress()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:start()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:finalize()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:cancelRoll()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:On_CHAT_MSG_SYSTEM()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:registerRoll()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:isNHToken()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:sortRolls()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:shoutWinner()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:shoutRolls()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

function TEST_StriLi.AutoRollAnalyser:increaseWinnerCountAndExpandItemHistory()
	UnitTest_vStartTest();

	--Test1
	UnitTest_vTestAssert(false);

	UnitTest_vFinishTest();
end

UnitTest_vSetupTests();
TEST_StriLi.AutoRollAnalyser:setItemID();
TEST_StriLi.AutoRollAnalyser:setTimeForRolls();
TEST_StriLi.AutoRollAnalyser:setItem();
TEST_StriLi.AutoRollAnalyser:getRollInProgress();
TEST_StriLi.AutoRollAnalyser:start();
TEST_StriLi.AutoRollAnalyser:finalize();
TEST_StriLi.AutoRollAnalyser:cancelRoll();
TEST_StriLi.AutoRollAnalyser:On_CHAT_MSG_SYSTEM();
TEST_StriLi.AutoRollAnalyser:registerRoll();
TEST_StriLi.AutoRollAnalyser:isNHToken();
TEST_StriLi.AutoRollAnalyser:sortRolls();
TEST_StriLi.AutoRollAnalyser:shoutWinner();
TEST_StriLi.AutoRollAnalyser:shoutRolls();
TEST_StriLi.AutoRollAnalyser:increaseWinnerCountAndExpandItemHistory();
UnitTest_vFinalizeTests();
